name: BGA Stats to Discord

on:
  schedule:
    - cron: "0 18 * * 0"   # Every Sunday at 18:00 UTC
    - cron: "0 18 * * 3"   # Every Wednesday at 18:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install requests beautifulsoup4

      - run: python bga_stats.py
        env:
          BGA_USERNAME: ${{ secrets.BGA_USERNAME }}
          BGA_PASSWORD: ${{ secrets.BGA_PASSWORD }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_BGA_STATS_WEBHOOK }}

      - name: Commit and push updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/bga_games_database.json
          git commit -m "Update bga_games_database.json [skip ci]" || echo "No changes to commit"
          git push
