name: FPL News to Discord

on:
  schedule:
    - cron: "0 2 * * *"   # every day at 18:00 PST
  workflow_dispatch:

jobs:
  post-news:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install praw requests

      - name: Run script
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          DISCORD_FPL_NEWS_WEBHOOK: ${{ secrets.DISCORD_FPL_NEWS_WEBHOOK }}
        run: python fpl_news.py
